language: node_js
node_js:
  - "8"
  - "10"
  - "11"

cache:
  directories:
    - .yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set scripts-prepend-node-path true

script:
  - yarn build
  - yarn eslint 
  - yarn test