name: Main CI Workflow

on: push


jobs:
  build-test-eslint-node-18:
    name: Build, Test & Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn eslint

  build-test-eslint-node-20:
    name: Build, Test & Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn eslint